version: "3.7"

services:
  xmeme-frontend:
    container_name: xmeme-frontend
    build:
      context: ./xmeme-frontend/
    ports:
      - 3000:3000
    volumes:
      - ./xmeme-frontend/:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    stdin_open: true
  xmeme-backend:
    container_name: xmeme-backend
    build:
      context: ./xmeme-backend/
    ports:
      - 5000:5000
    volumes:
      - ./xmeme-backend/:/server/
      - /server/node_modules